language: node_js
before_install:
  # Repo for Yarn
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn

install:
  - yarn install

cache: yarn

node_js:
  - 7
  - 6

services:
  - postgresql

before_script:
  - psql -c 'create database doc_man_test;' -U postgres
  - npm run db:migrate:test

after_script:
  - node node_modules/codeclimate-test-reporter/bin/codeclimate < coverage/lcov.info
